version: '3.3'

services:
  web-ngoldack:
    image: klakegg/hugo:latest
    command: server
    networks:
      - proxy
    environment:
      - ENV=production
    volumes:
      - ".:/src"
    labels:
      - traefik.enable=true
      - traefik.http.routers.web-ngoldack.rule=Host(`ngoldack.de`, `www.ngoldack.de`)
      - traefik.http.routers.web-ngoldack.entrypoints=https
      - traefik.http.services.web-ngoldack.loadbalancer.server.port=1313

networks:
  proxy:
    external: true