# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  clean:
    cmds:
      - rm -rf public/
    silent: true

  build:
    cmds:
      - hugo

  serve:
    cmds:
      - hugo server -w
